export type Service = { slug:string; title:string; eyebrow:string; summary:string; description:string; image:string; details:string[]; tone:string };
export const services: Service[] = [
 {slug:'building-painting',title:'نقاشی ساختمان',eyebrow:'Interior / Exterior',summary:'سطوحی آرام، تمیز و ماندگار برای هر فضای زندگی.',description:'از آماده‌سازی دقیق تا لایهٔ نهایی، رنگ‌آمیزی ساختمان را با نگاه یکدست به نور، بافت و معماری پیش می‌بریم.',image:'/media/aria-color-service-building-painting.webp.webp',details:['بازدید و بررسی سطح','ترمیم و زیرسازی تمیز','انتخاب پوشش متناسب با کاربری'],tone:'navy'},
 {slug:'decorative-painting',title:'نقاشی دکوراتیو',eyebrow:'Material / Detail',summary:'جزئیاتی که به دیوارها شخصیت می‌دهند.',description:'تکنیک‌های دکوراتیو و بافت‌های کنترل‌شده برای فضاهایی که قرار است به‌یاد بمانند؛ از پتینهٔ ظریف تا جلوه‌های معاصر.',image:'/media/aria-color-service-decorative-painting.webp.webp',details:['پتینه و بافت‌های ظریف','نمونه‌سازی روی سطح واقعی','اجرای جزئیات با هماهنگی طراحی'],tone:'gold'},
 {slug:'facade-painting',title:'رنگ‌آمیزی نما',eyebrow:'Facade / Weather',summary:'محافظت و زیبایی در اولین نگاه.',description:'رنگ‌آمیزی نما نیازمند شناخت نور، رطوبت و شرایط محیطی است. سیستم پوششی مناسب را برای دوام و ظاهر یکدست پیشنهاد می‌کنیم.',image:'/media/aria-color-service-facade-painting.webp.webp',details:['شست‌وشو و آماده‌سازی نما','آستر و پوشش مقاوم','کنترل یکنواختی در نور روز'],tone:'cream'},
 {slug:'office-painting',title:'رنگ‌آمیزی اداری',eyebrow:'Workplace / Focus',summary:'محیط کاری حرفه‌ای بدون اختلال در ریتم کسب‌وکار.',description:'با برنامه‌ریزی مرحله‌ای و انتخاب رنگی که با نور و هویت برند هماهنگ باشد، فضای کار شما را تازه می‌کنیم.',image:'/media/aria-color-service-office-painting.webp.webp',details:['زمان‌بندی خارج از ساعت کاری','پوشش کم‌بو برای محیط‌های داخلی','تحویل مرتب و پاکیزه'],tone:'navy'},
 {slug:'ceiling-painting',title:'رنگ‌آمیزی سقف',eyebrow:'Light / Proportion',summary:'سقف، بخشی از معماری است؛ نه پس‌زمینه‌ای فراموش‌شده.',description:'با کنترل انعکاس نور و ترمیم ترک‌ها، سقف را به عنصری برای تعادل و روشنایی فضا تبدیل می‌کنیم.',image:'/media/aria-color-service-ceiling-painting.webp.webp',details:['ترمیم ترک و لکه','انتخاب میزان انعکاس','لبه‌گیری دقیق'],tone:'cream'},
 {slug:'paint-restoration',title:'بازسازی رنگ',eyebrow:'Restore / Respect',summary:'احیای کیفیت، بدون پاک‌کردن هویت فضا.',description:'رنگ‌های قدیمی و سطوح آسیب‌دیده را با ارزیابی مرحله‌ای ترمیم می‌کنیم؛ هرجا حفظ‌کردن بهتر از پوشاندن باشد، همان را انتخاب می‌کنیم.',image:'/media/aria-color-service-paint-restoration.webp.webp',details:['تشخیص آسیب و رطوبت','ترمیم موضعی','هماهنگ‌سازی رنگ'],tone:'gold'},
 {slug:'commercial-painting',title:'پروژه‌های تجاری',eyebrow:'Retail / Hospitality',summary:'رنگی که تجربهٔ مشتری را کامل می‌کند.',description:'برای فروشگاه، کافه و فضاهای پذیرایی، اجرای دقیق را با درک مسیر حرکت و نورپردازی ترکیب می‌کنیم.',image:'/media/aria-color-portfolio-commercial.webp.webp',details:['هماهنگی با تیم طراحی','اجرای کم‌وقفه','نمونهٔ تأییدشده پیش از اجرا'],tone:'navy'},
 {slug:'color-consultation',title:'مشاوره انتخاب رنگ',eyebrow:'Palette / Feeling',summary:'پیش از اجرا، رنگ را در نور واقعی فضا می‌بینیم.',description:'جلسه‌ای برای شناخت نور، متریال و حال‌وهوای مطلوب شما؛ خروجی می‌تواند یک پالت پیشنهادی روشن و قابل اجرا باشد.',image:'/media/aria-color-color-selection.webp.webp',details:['بررسی نور طبیعی و مصنوعی','پالت‌های پیشنهادی','نمونه‌سازی پیش از تصمیم'],tone:'gold'},
];
export const projects = [
 {slug:'آپارتمان-آرام',title:'آپارتمان آرام',category:'مسکونی',summary:'ترکیب کرم گرم، سرمه‌ای عمیق و نور طبیعی.',image:'/media/aria-color-portfolio-living-room.webp.webp',before:'/media/aria-color-before-renovation.webp.webp',after:'/media/aria-color-after-renovation.webp.webp'},
 {slug:'اتاق-خواب-نرم',title:'اتاق خواب نرم',category:'مسکونی',summary:'رنگی کم‌کنتراست برای شروع روزی آرام.',image:'/media/aria-color-portfolio-bedroom.webp.webp'},
 {slug:'دفتر-با-تمرکز',title:'دفتر با تمرکز',category:'اداری',summary:'تعادل میان تمرکز، انرژی و هویت سازمانی.',image:'/media/aria-color-portfolio-office.webp.webp'},
 {slug:'فضای-تجاری-معاصر',title:'فضای تجاری معاصر',category:'تجاری',summary:'سطحی یکدست که محصول را در مرکز نگه می‌دارد.',image:'/media/aria-color-portfolio-commercial.webp.webp'},
];
