import {PrismaClient} from '@prisma/client';import {randomBytes} from 'node:crypto';import {writeFile} from 'node:fs/promises';
const database=process.env.TEST_DATABASE_URL,origin=process.env.TEST_ORIGIN||'http://localhost:3090';if(!database||!new URL(database).pathname.endsWith('_test')||new URL(origin).hostname!=='localhost')throw Error('Only an explicitly configured isolated *_test database and localhost server are allowed.');
const db=new PrismaClient({datasources:{db:{url:database}}});const checks:{name:string;passed:boolean}[]=[];function assert(value:unknown,name:string){checks.push({name,passed:Boolean(value)});if(!value)throw Error(name)}
async function call(path:string,data?:unknown,cookie='',method='POST',requestOrigin=origin){return fetch(origin+path,{method:data===undefined?'GET':method,headers:{'Content-Type':'application/json',Origin:requestOrigin,...(cookie?{Cookie:cookie}:{})},...(data===undefined?{}:{body:JSON.stringify(data)}),redirect:'manual'})}
const password='Test-'+randomBytes(18).toString('base64url');const suffix=Date.now();let cookie='',cookie2='',adminCookie='';
try{
 await db.rateLimit.deleteMany();
 let r=await call('/dashboard');assert(r.status===307&&r.headers.get('location')==='/login','Anonymous dashboard redirects to login');
 r=await call('/api/auth/register',{email:`a-${suffix}@example.test`,password,name:'مشتری آزمایشی یک',consent:true,role:'SUPER_ADMIN'});assert(r.status===201,'Registration persisted');cookie=r.headers.get('set-cookie')!.split(';')[0];assert(r.headers.get('set-cookie')?.includes('HttpOnly')&&r.headers.get('set-cookie')?.includes('Secure'),'Session cookie HttpOnly and Secure');
 const user=await db.user.findUniqueOrThrow({where:{email:`a-${suffix}@example.test`}});assert(user.role==='USER','Client cannot assign privileged role');assert(user.passwordHash!==password&&user.passwordHash.startsWith('scrypt:'),'Password is hashed with scrypt');const sessions=await db.session.findMany({where:{userId:user.id}});assert(sessions.length===1&&!cookie.includes(sessions[0].tokenHash),'Database stores hashed session token only');
 r=await call('/dashboard',undefined,cookie);assert(r.status===200,'Authenticated dashboard renders');
 r=await call('/api/requests',{kind:'CONSULTATION',name:'نام خصوصی پروژه یک',phone:'09123456789',projectType:'بازسازی اختصاصی آزمایشی',area:85,description:'یادداشت خصوصی مشتری یک',consent:'on'},cookie);assert(r.status===201,'Authenticated consultation stored');const request=(await r.json()) as {id:string};const saved=await db.serviceRequest.findUniqueOrThrow({where:{id:request.id}});assert(saved.userId===user.id,'Request bound to authenticated user on server');assert(await db.notification.count({where:{userId:user.id}})>0,'Customer receives stored receipt notification');
 r=await call('/api/auth/register',{email:`b-${suffix}@example.test`,password,name:'مشتری آزمایشی دو',consent:true});assert(r.status===201,'Second user created');cookie2=r.headers.get('set-cookie')!.split(';')[0];
 r=await call(`/dashboard/requests/${request.id}`,undefined,cookie2);const otherHtml=await r.text();assert(!otherHtml.includes('یادداشت خصوصی مشتری یک'),'Another customer cannot read private request data');
 r=await call(`/api/admin/requests/${request.id}`,{status:'COMPLETED',updatedAt:saved.updatedAt.toISOString()},cookie2,'PATCH');assert(r.status===403,'User cannot call admin mutation');
 await db.user.update({where:{email:`b-${suffix}@example.test`},data:{role:'EDITOR'}});r=await call(`/api/admin/requests/${request.id}`,{status:'COMPLETED',updatedAt:saved.updatedAt.toISOString()},cookie2,'PATCH');assert(r.status===403,'Editor cannot manage private customer requests');
 r=await call('/api/profile',{name:'نام ویرایش شده',phone:'09121111111'},cookie,'PATCH');assert(r.status===200,'Profile editing works');assert((await db.profile.findUnique({where:{userId:user.id}}))?.name==='نام ویرایش شده','Profile change persisted');
 r=await call('/api/auth/register',{email:`admin-${suffix}@example.test`,password,name:'مدیر آزمایشی',consent:true});assert(r.status===201,'Admin test account created as regular user');adminCookie=r.headers.get('set-cookie')!.split(';')[0];await db.user.update({where:{email:`admin-${suffix}@example.test`},data:{role:'ADMIN'}});
 r=await call('/admin',undefined,adminCookie);assert(r.status===200,'Admin dashboard renders real counts');
 r=await call(`/api/admin/requests/${request.id}`,{status:'UNDER_REVIEW',updatedAt:saved.updatedAt.toISOString()},adminCookie,'PATCH');assert(r.status===200,'Admin status mutation succeeds');
 r=await call(`/api/admin/requests/${request.id}`,{status:'COMPLETED',updatedAt:saved.updatedAt.toISOString()},adminCookie,'PATCH');assert(r.status===409,'Stale concurrent update is rejected');assert((await db.serviceRequest.findUnique({where:{id:request.id}}))?.status==='UNDER_REVIEW','Status persists correctly');
 const notification=await db.notification.findFirstOrThrow({where:{userId:user.id,title:'وضعیت درخواست شما تغییر کرد'}});r=await call('/api/notifications',{id:notification.id},cookie2,'PATCH');assert(r.status===200&&(await db.notification.findUnique({where:{id:notification.id}}))?.readAt===null,'Other user cannot mark private notification read');r=await call('/api/notifications',{id:notification.id},cookie,'PATCH');assert(r.status===200&&Boolean((await db.notification.findUnique({where:{id:notification.id}}))?.readAt),'Owner can mark notification read');
 r=await call('/api/profile',{name:'forged'},cookie,'PATCH','https://untrusted.example');assert(r.status===403,'Cross-origin mutation rejected');
 r=await call('/api/requests',{kind:'VISIT',name:'آزمایش',phone:'09123456789',projectType:'آزمایش',consent:'on'},cookie);assert(r.status===422,'Visit requires date and address');
 r=await call('/api/requests',{kind:'QUOTE',name:'آزمایش',phone:'not-phone',projectType:'آزمایش',consent:'on'},cookie);assert(r.status===422,'Invalid phone rejected on server');
 r=await call('/api/profile',{name:'x'.repeat(20000)},cookie,'PATCH');assert(r.status===413,'Oversized streamed body rejected');
 r=await call('/api/auth/logout',{},cookie);assert(r.status===200,'Logout succeeds');assert(await db.session.count({where:{userId:user.id}})===0,'Logout invalidates database session');r=await call('/dashboard',undefined,cookie);assert(r.status===307,'Logged-out cookie no longer authenticates');
 r=await call('/api/auth/login',{email:user.email,password:'incorrect-password-123'});assert(r.status===401,'Wrong password rejected');r=await call('/api/auth/login',{email:user.email,password});assert(r.status===200,'Correct password login succeeds');cookie=r.headers.get('set-cookie')!.split(';')[0];await db.session.updateMany({where:{userId:user.id},data:{expiresAt:new Date(Date.now()-1000)}});r=await call('/dashboard',undefined,cookie);assert(r.status===307,'Expired session rejected');
 for(let i=0;i<9;i++)r=await call('/api/auth/login',{email:`missing-${suffix}@example.test`,password});assert(r!.status===429,'Repeated authentication attempts rate limited');
 const result={testedAt:new Date().toISOString(),checks,passed:checks.length};await writeFile(process.env.TEST_REPORT||'/tmp/aria-integration-report.json',JSON.stringify(result,null,2));console.log(JSON.stringify({passed:checks.length,failures:checks.filter(c=>!c.passed)}));
}finally{await db.$disconnect()}
